import { useEffect, useId, useMemo, useRef, useState } from 'react';
import { motion } from 'framer-motion';
import {
  Lightbulb, Clock, CheckCircle2, Flame, Star, Target,
  Brain, GitBranch, Activity, Sparkles,
} from 'lucide-react';
import { useStore } from '../store/useStore';
import { useWorkLogStore } from '../store/useWorkLogStore';
import { useCollaborationStore } from '../store/useCollaborationStore';
import { api } from '../utils/api';
import { timerEngine } from '../utils/timerEngine';
import { mapSession, type MemorySession } from '../lib/memorySelectors';
import {
  selectDailyInsights, selectWeeklyInsights, selectWorkPatternInsights,
  selectTaskInsights, selectKnowledgeInsights, type DailyInsight,
} from '../lib/insightsSelectors';
import { SkeletonCard } from '../components/ui/Skeleton';
import { EmptyState } from '../components/ui/EmptyState';

// ── PI-1.1/1.2/1.3/1.4/1.5: Personal Insights page (Phase PI) ─────────────────
// Companion to Reports, not a replacement. Where Reports answers "what happened"
// with charts and KPIs, Insights answers "what does it mean" in plain words.
// Every card is generated by the pure selectors from the same analytics data
// Reports uses — no AI, no invented numbers. Periods with too little data render
// an honest "Not enough data yet." state instead of a weak insight. PI-1.2 adds
// the ISO-week layer (This Week's Insights); PI-1.3 adds the Work Pattern layer
// (peak window, most focused day, focus block length over the last 4 weeks);
// PI-1.4 adds the Task layer (overdue/stale/priority/subtasks); PI-1.5 adds the
// Knowledge layer (docs, decisions, lessons, links from the cumulative base).

const CONFIDENCE_STYLE: Record<DailyInsight['confidence'], string> = {
  high: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/20',
  medium: 'text-amber-400 bg-amber-500/10 border-amber-500/20',
  low: 'text-zinc-400 bg-zinc-500/10 border-zinc-500/20',
};

const CATEGORY_ICON: Record<string, typeof Clock> = {
  Focus: Clock,
  'Work Habits': Activity,
  Tasks: CheckCircle2,
  Consistency: Flame,
  Context: GitBranch,
  Knowledge: Brain,
  Reflection: Star,
  Productivity: Target,
};

function InsightBadges({ insight }: { insight: DailyInsight }) {
  const Icon = CATEGORY_ICON[insight.category] ?? Lightbulb;
  return (
    <div className="flex flex-wrap items-center gap-1.5">
      <span className="inline-flex items-center gap-1 text-[10px] font-semibold uppercase tracking-wider text-surface-400 bg-surface-800 px-2 py-0.5 rounded-md">
        <Icon size={11} />
        {insight.category}
      </span>
      <span className={`inline-flex items-center text-[10px] font-semibold uppercase tracking-wider px-2 py-0.5 rounded-md border ${CONFIDENCE_STYLE[insight.confidence]}`}>
        {insight.confidence} confidence
      </span>
      <span className="text-[10px] text-surface-500 font-medium">{insight.period.label}</span>
    </div>
  );
}

function InsightMetrics({ metrics }: { metrics: DailyInsight['metrics'] }) {
  return (
    <div className="mt-3">
      <h4 className="sr-only">Supporting metrics</h4>
      <ul className="flex flex-wrap gap-2">
        {metrics.map((m) => (
          <li key={m.label} className="rounded-lg border border-surface-800 bg-surface-850/60 px-2.5 py-1.5">
            <p className="text-[10px] text-surface-500 font-medium uppercase tracking-wide">{m.label}</p>
            <p className="text-sm font-mono font-semibold text-surface-100">{m.value}</p>
          </li>
        ))}
      </ul>
    </div>
  );
}

function InsightAction({ insight }: { insight: DailyInsight }) {
  if (!insight.action) return null;
  return (
    <div className="mt-4 flex items-start gap-2 rounded-xl border border-brand-500/20 bg-brand-500/5 px-3 py-2.5">
      <Sparkles size={14} className="text-brand-400 mt-0.5 flex-shrink-0" />
      <div>
        <p className="text-xs font-bold text-brand-300">{insight.action.label}</p>
        <p className="text-[11px] text-surface-400 leading-relaxed">{insight.action.detail}</p>
      </div>
    </div>
  );
}

function InsightCard({ insight, accent }: { insight: DailyInsight; accent: string }) {
  return (
    <motion.article
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.25, ease: [0.25, 0.46, 0.45, 0.94] }}
      className="rounded-2xl border border-surface-800 bg-surface-900 p-5 hover:border-surface-700 transition-all flex flex-col"
    >
      <div className="flex items-start justify-between gap-3 mb-2">
        <h3 className="text-sm font-bold text-surface-50">{insight.title}</h3>
        <span className="w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0" style={{ backgroundColor: `${accent}18` }}>
          <span className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: accent }} aria-hidden="true" />
        </span>
      </div>
      <InsightBadges insight={insight} />
      <p className="text-[13px] leading-relaxed text-surface-300 mt-3">{insight.observation}</p>
      <InsightMetrics metrics={insight.metrics} />
      <div className="mt-auto">
        <InsightAction insight={insight} />
      </div>
    </motion.article>
  );
}

function FeaturedInsight({ insight, accent, eyebrow = 'Most Important' }: { insight: DailyInsight; accent: string; eyebrow?: string }) {
  const Icon = CATEGORY_ICON[insight.category] ?? Lightbulb;
  const titleId = useId();
  return (
    <motion.article
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3, ease: [0.25, 0.46, 0.45, 0.94] }}
      className="relative rounded-2xl border border-brand-500/25 bg-gradient-to-br from-brand-500/10 to-surface-900 p-6 overflow-hidden"
      aria-labelledby={titleId}
    >
      <div className="absolute -top-16 -right-16 w-56 h-56 rounded-full opacity-10 pointer-events-none" style={{ backgroundColor: accent }} />
      <div className="flex items-center gap-2 mb-4">
        <span className="w-9 h-9 rounded-xl flex items-center justify-center text-brand-400" style={{ backgroundColor: `${accent}18` }}>
          <Icon size={16} />
        </span>
        <div>
          <p className="text-[10px] font-bold uppercase tracking-wider text-brand-400">{eyebrow}</p>
          <p className="text-[10px] text-surface-500 font-medium">{insight.period.label}</p>
        </div>
      </div>
      <h2 id={titleId} className="text-lg lg:text-xl font-display font-extrabold text-surface-50 mb-2">
        {insight.title}
      </h2>
      <p className="text-sm leading-relaxed text-surface-300 max-w-3xl">{insight.observation}</p>
      <InsightMetrics metrics={insight.metrics} />
      <InsightAction insight={insight} />
    </motion.article>
  );
}

export function InsightsPage() {
  const { tasks, journals, profile, theme, dataLoading, activeTaskId, activeSessionId, activeTimerState, currentSessionStart } = useStore();
  const { todayLog, activeLogs, closedLogs, loadActive, loadClosed, loadToday } = useWorkLogStore();
  const docs = useCollaborationStore((s) => s.docs);

  const [apiSessions, setApiSessions] = useState<MemorySession[]>([]);
  const [loadingSessions, setLoadingSessions] = useState(true);
  const [timerTick, setTimerTick] = useState(0);
  const prevTimerRef = useRef(activeTimerState);

  useEffect(() => {
    if (activeTimerState === 'idle') {
      prevTimerRef.current = 'idle';
      return;
    }
    const id = setInterval(() => setTimerTick((t) => t + 1), 1000);
    return () => clearInterval(id);
  }, [activeTimerState]);

  useEffect(() => {
    if (prevTimerRef.current !== 'idle' && activeTimerState === 'idle') {
      api.sessions.list().then((docs) => setApiSessions(docs.map(mapSession))).catch(() => {});
    }
    prevTimerRef.current = activeTimerState;
  }, [activeTimerState]);

  useEffect(() => {
    let cancelled = false;
    setLoadingSessions(true);
    api.sessions.list()
      .then((docs: Record<string, any>[]) => { if (!cancelled) setApiSessions(docs.map(mapSession)); })
      .catch(() => { if (!cancelled) setApiSessions([]); })
      .finally(() => { if (!cancelled) setLoadingSessions(false); });
    return () => { cancelled = true; };
  }, [activeTaskId]);

  useEffect(() => {
    loadActive();
    loadClosed();
    loadToday();
  }, []);

  const liveSessions = useMemo<MemorySession[]>(() => {
    if (activeTimerState === 'idle' || !activeTaskId || !currentSessionStart) return [];
    const activeTime = timerEngine.getElapsedMs();
    if (activeTime <= 0) return [];
    const snapshot = timerEngine.getSnapshot();
    const openPause = snapshot.timerState === 'paused' && snapshot.pauseStart
      ? Math.max(0, Date.now() - snapshot.pauseStart)
      : 0;
    return [{
      id: `live_${activeTaskId}_${activeSessionId ?? 'current'}`,
      taskId: activeTaskId,
      startTime: currentSessionStart,
      endTime: null,
      activeTime,
      totalPauseDuration: snapshot.totalPauseDuration + openPause,
      pauseCount: 0,
      isActive: true,
      focusScore: 100,
      pauseLog: [],
    }];
  }, [activeTaskId, activeSessionId, activeTimerState, currentSessionStart, timerTick]);

  const sessions = useMemo(() => {
    const liveIds = new Set(liveSessions.map((s) => s.id.replace(/^live_[^_]+_/, '')));
    const completed = apiSessions.filter((s) => !liveIds.has(s.id));
    return [...completed, ...liveSessions].filter((s) => s.taskId && s.activeTime > 0);
  }, [apiSessions, liveSessions]);

  const workLogs = useMemo(() => {
    const seen = new Set<string>();
    return [todayLog, ...activeLogs, ...closedLogs].filter((l): l is NonNullable<typeof todayLog> => {
      if (!l) return false;
      if (seen.has(l._id)) return false;
      seen.add(l._id);
      return true;
    });
  }, [todayLog, activeLogs, closedLogs]);

  const view = useMemo(
    () => selectDailyInsights({ sessions, tasks, journals, workLogs, dailyGoalMs: profile?.dailyGoal ?? 0 }),
    [sessions, tasks, journals, workLogs, profile?.dailyGoal],
  );

  const week = useMemo(
    () => selectWeeklyInsights({ sessions, tasks, journals, workLogs, dailyGoalMs: profile?.dailyGoal ?? 0 }),
    [sessions, tasks, journals, workLogs, profile?.dailyGoal],
  );

  const pattern = useMemo(
    () => selectWorkPatternInsights({ sessions, tasks, journals, workLogs, dailyGoalMs: profile?.dailyGoal ?? 0 }),
    [sessions, tasks, journals, workLogs, profile?.dailyGoal],
  );

  const task = useMemo(
    () => selectTaskInsights({ sessions, tasks, journals, workLogs, dailyGoalMs: profile?.dailyGoal ?? 0 }),
    [tasks],
  );

  const knowledge = useMemo(
    () => selectKnowledgeInsights({ docs, workLogs, journals }),
    [docs, workLogs, journals],
  );

  const accent = theme?.accentColor || '#0ea5e9';
  const loading = loadingSessions && sessions.length === 0;

  return (
    <div className="p-6 lg:p-8 max-w-[1400px] mx-auto">
      <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} className="mb-6">
        <div className="flex items-center gap-2.5 mb-1">
          <span className="w-9 h-9 rounded-xl bg-brand-500/10 border border-brand-500/20 flex items-center justify-center">
            <Lightbulb size={16} className="text-brand-400" />
          </span>
          <div>
            <h1 className="text-2xl lg:text-3xl font-display font-extrabold text-surface-50 tracking-tight">Personal Insights</h1>
            <p className="text-surface-400 text-sm mt-0.5">What your tracked data means — plainly and honestly.</p>
          </div>
        </div>
      </motion.div>

      {loading || dataLoading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4" aria-busy="true" aria-label="Loading insights">
          {Array.from({ length: 6 }).map((_, i) => <SkeletonCard key={i} />)}
        </div>
      ) : !view.hasData && !week.hasData && !pattern.hasData && !task.hasData && !knowledge.hasData ? (
        <EmptyState
          className="rounded-2xl border border-surface-800 bg-surface-900"
          icon={<Lightbulb size={28} />}
          title="Not enough data yet."
          description="Start a focus session, complete a task, or write a journal entry and your daily, weekly, work-pattern, task, and knowledge insights will appear here."
          hint="Insights are generated only from real tracked data — nothing is guessed."
        />
      ) : (
        <div className="space-y-6">
          {view.hasData && (
            <>
              {view.mostImportant && <FeaturedInsight insight={view.mostImportant} accent={accent} />}

              <section aria-labelledby="insights-today-heading">
                <div className="flex items-center gap-2 mb-4">
                  <h2 id="insights-today-heading" className="text-sm font-bold uppercase tracking-wider text-surface-400">Today's Insights</h2>
                  <span className="text-[10px] text-surface-500 font-medium">{view.sessionCount} session{view.sessionCount === 1 ? '' : 's'} today</span>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
                  {view.todays.map((insight) => <InsightCard key={insight.id} insight={insight} accent={accent} />)}
                </div>
              </section>
            </>
          )}

          {week.hasData && (
            <section aria-labelledby="insights-week-heading">
              <div className="flex items-center gap-2 mb-4">
                <h2 id="insights-week-heading" className="text-sm font-bold uppercase tracking-wider text-surface-400">This Week's Insights</h2>
                <span className="text-[10px] text-surface-500 font-medium">{week.sessionCount} session{week.sessionCount === 1 ? '' : 's'} this week · {week.periodLabel}</span>
              </div>
              {week.mostImportant && (
                <div className="mb-4">
                  <FeaturedInsight insight={week.mostImportant} accent={accent} eyebrow="Weekly Focus" />
                </div>
              )}
              <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
                {week.weekly.map((insight) => <InsightCard key={insight.id} insight={insight} accent={accent} />)}
              </div>
            </section>
          )}

          {task.hasData && (
            <section aria-labelledby="insights-task-heading">
              <div className="flex items-center gap-2 mb-4">
                <h2 id="insights-task-heading" className="text-sm font-bold uppercase tracking-wider text-surface-400">Task Insights</h2>
                <span className="text-[10px] text-surface-500 font-medium">{task.openCount} open task{task.openCount === 1 ? '' : 's'} · {task.periodLabel}</span>
              </div>
              {task.mostImportant && (
                <div className="mb-4">
                  <FeaturedInsight insight={task.mostImportant} accent={accent} eyebrow="Task Focus" />
                </div>
              )}
              <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
                {task.tasks.map((insight) => <InsightCard key={insight.id} insight={insight} accent={accent} />)}
              </div>
            </section>
          )}

          {pattern.hasData && (
            <section aria-labelledby="insights-pattern-heading">
              <div className="flex items-center gap-2 mb-4">
                <h2 id="insights-pattern-heading" className="text-sm font-bold uppercase tracking-wider text-surface-400">Work Pattern Insights</h2>
                <span className="text-[10px] text-surface-500 font-medium">{pattern.sessionCount} session{pattern.sessionCount === 1 ? '' : 's'} · {pattern.periodLabel}</span>
              </div>
              {pattern.mostImportant && (
                <div className="mb-4">
                  <FeaturedInsight insight={pattern.mostImportant} accent={accent} eyebrow="Pattern Focus" />
                </div>
              )}
              <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
                {pattern.patterns.map((insight) => <InsightCard key={insight.id} insight={insight} accent={accent} />)}
              </div>
            </section>
          )}

          {knowledge.hasData && (
            <section aria-labelledby="insights-knowledge-heading">
              <div className="flex items-center gap-2 mb-4">
                <h2 id="insights-knowledge-heading" className="text-sm font-bold uppercase tracking-wider text-surface-400">Knowledge Insights</h2>
                <span className="text-[10px] text-surface-500 font-medium">{knowledge.total} item{knowledge.total === 1 ? '' : 's'} · {knowledge.periodLabel}</span>
              </div>
              {knowledge.mostImportant && (
                <div className="mb-4">
                  <FeaturedInsight insight={knowledge.mostImportant} accent={accent} eyebrow="Knowledge Focus" />
                </div>
              )}
              <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
                {knowledge.knowledge.map((insight) => <InsightCard key={insight.id} insight={insight} accent={accent} />)}
              </div>
            </section>
          )}
        </div>
      )}
    </div>
  );
}
